const products = [
    {
        _id: '111111111111111111111111',
        name: 'Hello New World T-shirt',
        category: 'Shirts',
        image: '/images/product-1.jpg',
        price: 60,
        brand: 'Nike',
        rating: 3.5,
        description: 'Dreamville Records t-shirt, only available at Urban Outfitters. Heavyweight cotton is cut in a standard fit featuring a text graphic across the chest and finished with a banded crew neck.',
        numReviews: 8,
        countInStock: 6,
    },
    {
        _id: '222222222222222222222222',
        name: 'Hustle the muscle',
        category: 'Shirts',
        image: 'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        price: 30,
        brand: 'Nike',
        rating: 5,
        description: 'Dreamville Records t-shirt, only available at Urban Outfitters. Heavyweight cotton is cut in a standard fit featuring a text graphic across the chest and finished with a banded crew neck.',
        numReviews: 16,
        countInStock: 6,
    },
    {
        _id: '333333333333333333333333',
        name: 'Addicted To Code T-shirt',
        category: 'Shirts',
        image: 'https://images-na.ssl-images-amazon.com/images/I/71EagW9qn2L._AC_UY879_.jpg',
        price: 60,
        brand: 'Nike',
        rating: 2.5,
        description: 'Dreamville Records t-shirt, only available at Urban Outfitters. Heavyweight cotton is cut in a standard fit featuring a text graphic across the chest and finished with a banded crew neck.',
        numReviews: 4,
        countInStock: 6,
    },
    {
        _id: '444444444444444444444444',
        name: 'Developer Cap',
        category: 'Shirts',
        image: 'https://images.pexels.com/photos/2005355/pexels-photo-2005355.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
        price: 60,
        brand: 'Nike',
        rating: 2,
        description: 'Dreamville Records t-shirt, only available at Urban Outfitters. Heavyweight cotton is cut in a standard fit featuring a text graphic across the chest and finished with a banded crew neck.',
        numReviews: 5,
        countInStock: 6,
    },
    {
        _id: '555555555555555555555555',
        name: 'Developer Studio Polo',
        category: 'Shirts',
        image: '/images/product-1.jpg',
        price: 60,
        brand: 'Nike',
        rating: 1,
        description: 'Dreamville Records t-shirt, only available at Urban Outfitters. Heavyweight cotton is cut in a standard fit featuring a text graphic across the chest and finished with a banded crew neck.',
        numReviews: 20,
        countInStock: 6,
    },
    {
        _id: '666666666666666666666666',
        name: 'Full Zip Running Shirts',
        category: 'Shirts',
        image: '/images/product-1.jpg',
        price: 60,
        brand: 'Nike',
        rating: 4.5,
        description: 'Dreamville Records t-shirt, only available at Urban Outfitters. Heavyweight cotton is cut in a standard fit featuring a text graphic across the chest and finished with a banded crew neck.',
        numReviews: 2,
        countInStock: 6,
    },
];

export default products;
